//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniFootball.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int id { get; set; }
        public int Home_team_id { get; set; }
        public int Away_team_id { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<int> HomeScore { get; set; }
        public Nullable<int> AwayScore { get; set; }
        public Nullable<int> WinnerTeamId { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
